import React from 'react';
import { SectionWrapper } from './ui/SectionWrapper';
import { Star, Quote } from 'lucide-react';

export const Testimonials: React.FC = () => {
  return (
    <SectionWrapper className="bg-gradient-to-b from-black to-[#0a0000]">
       <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
          {/* Review Card */}
          <div className="p-10 rounded-sm bg-glass-bg border border-glass-border relative shadow-[0_0_30px_rgba(0,0,0,0.8)]">
            <Quote className="absolute top-8 right-8 text-white/5 w-20 h-20" />
            <div className="flex gap-1 text-yellow-600 mb-6 drop-shadow-md">
              {[1,2,3,4,5].map(i => <Star key={i} fill="currentColor" size={16} />)}
            </div>
            <p className="text-gray-300 text-lg leading-relaxed mb-8 relative z-10 font-serif italic">
              "The quality of images generated by Aionyx is simply unmatched. It captures the eerie, nostalgic essence I was looking for perfectly. It's like having a portal to another dimension."
            </p>
            <div className="flex items-center gap-4">
               <img src="https://picsum.photos/100/100?random=88" alt="User" className="w-12 h-12 rounded border border-stranger-red grayscale hover:grayscale-0 transition-all" />
               <div>
                 <h4 className="font-bold text-white font-display tracking-wider">Avery Davis</h4>
                 <p className="text-xs text-stranger-red uppercase">Aionyx Power User</p>
               </div>
            </div>
          </div>

          {/* Right Side Info */}
          <div className="space-y-8">
             <h2 className="text-4xl md:text-5xl font-display font-bold leading-tight text-stranger-glow">
               The AI Revolution, <br />
               Told By Survivors
             </h2>
             <div className="flex gap-6 border-b border-white/10 pb-4">
               <button className="text-white border-b-2 border-stranger-red pb-4 -mb-4.5 font-bold uppercase tracking-widest">Client Reviews</button>
               <button className="text-gray-600 hover:text-white transition-colors pb-4 font-bold uppercase tracking-widest">Google Reviews</button>
             </div>
             
             <div className="flex gap-1 text-yellow-600">
                {[1,2,3,4,5].map(i => <Star key={i} fill="currentColor" size={20} />)}
             </div>
             <p className="text-gray-400 font-serif">
               Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.
             </p>

             <div className="flex items-center gap-4 p-4 rounded bg-white/5 border border-white/10 w-fit hover:border-stranger-red/30 transition-colors">
                <img src="https://picsum.photos/100/100?random=99" alt="Team" className="w-10 h-10 rounded grayscale" />
                <div>
                  <h5 className="font-bold text-sm text-white">Andrew Zeus</h5>
                  <p className="text-xs text-gray-500">Our Team</p>
                </div>
                <Quote className="text-stranger-red ml-4" size={20} />
             </div>
          </div>
       </div>
    </SectionWrapper>
  );
};